apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testazurenodejs0613 
  description: Secure Supply Chain Example for Node.js+Express REST API with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=testazurenodejs0613
    backstage.io/kubernetes-id: testazurenodejs0613 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: xjiangorg/testazurenodejs0613
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: xjiangorg.testazurenodejs0613
    quay.io/repository-slug: quay_xjiang/testazurenodejs0613
  tags: ["nodejs", "express", "ubi8", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 